//
//  ContactFormModels.swift
//  SantanderInvest
//
//  Created by Bruno Villanova on 29/05/18.
//  Copyright (c) 2018 Santander. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ContactForm
{
  
  struct ContactFormField {
    var fieldId: Int
    var value: String?
  }
  
  enum FetchCells
  {
    struct Request
    {
    }
    struct Response
    {
      var cells: [FormCell]?
      var error: Error?
    }
    struct ViewModel
    {
      var formCells: [FormCell]
    }
  }
  
  enum SendContactForm {
    struct Request {
    }
    struct Response {
      var success: Bool?
    }
    struct ViewModel
    {
      var formCells: [FormCell]
    }
  }
  
  enum UpdateContactForm {
    struct Request {
      var contactFormFields: [ContactFormField]
    }
    struct Response {
      var cells: [FormCell]
    }
    struct ViewModel
    {
      var formCells: [FormCell]
    }
  }
}
